version: '3'
services:
  # Laravel Backend con PHP 8
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  # MySQL Database con la última versión
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app-network

  # Adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
